version: '3'

services:
  shairport-sync:
    image: mikebrady/shairport-sync:latest
    container_name: shairport-sync
    network_mode: host
    restart: on-failure:5
    devices:
      - "/dev/snd" # ALSA device
    volumes:
      - /srv/shairport-sync/shairport-sync.conf:/etc/shairport-sync.conf
    logging:
      options:
        max-size: "200k"
        max-file: "10"

