version: "3"
services:
  cloudflare-ddns:
    image: docker.io/favonia/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    network_mode: host
    cap_add:
      - SETUID
      - SETGID
    cap_drop:
      - all
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
    env_file:
      - ./cloudflare-ddns.env
    deploy:
      resources:
        limits:
          memory: 100M
    restart: always
    labels:
      io.containers.autoupdate: "registry"

      
