---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    hostname: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /srv/homelab/heimdall:/config
    ports:
      - 80:80
      - 443:443
    dns: 10.0.0.180
    deploy:
      resources:
        limits:
          memory: 100M    
    restart: on-failure:5
