version: '3'

services:
  shairport-sync:
    image: docker.io/mikebrady/shairport-sync:latest
    container_name: shairport-sync
    network_mode: host
    devices:
      - "/dev/snd" # ALSA device
    volumes:
      - ./shairport-sync.conf:/etc/shairport-sync.conf:z
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      resources:
        limits:
          memory: 100M
    restart: always
    labels:
      io.containers.autoupdate: "registry"
