version: '3'

services:
  outdoor_speakers:
    image: mikebrady/shairport-sync:latest
    container_name: airplay_name # Choose a name that will show up on your airplay devices list.
    network_mode: host
    restart: unless-stopped
    devices:
      - "/dev/snd" # ALSA device
    volumes:
      - /srv/shairport-sync/shairport-sync.conf:/etc/shairport-sync.conf
    logging:
      options:
        max-size: "200k"
        max-file: "10"

