version: "3"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  unbound:
    image: klutchell/unbound:latest
    container_name: unbound
    hostname: unbound
    networks:
      private_network:
        ipv4_address: 10.2.0.10
    deploy:
      resources:
        limits:
          memory: 100M
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      private_network:
        ipv4_address: 10.2.0.11
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80/tcp"
#      - 67:67/udp # Only required if you are using Pi-hole as your DHCP server.
#    cap_add:
#      - NET_ADMIN # Only required if you are using Pi-hole as your DHCP server.
    dns:
      - 127.0.0.1
      - 10.2.0.10  # Points to unbound
    environment:
      ServerIP: 10.2.0.11  # Internal IP of pihole
      DNS1: 10.2.0.10  # Unbound IP
      DNS2: 10.2.0.10  # If we don't specify two, it will auto pick google.
    env_file:
      - ./pihole.env
    deploy:
      resources:
        limits:
          memory: 250M
    restart: unless-stopped
    depends_on: [unbound]

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    hostname: wg-easy
    volumes:
      - ./wg-easy:/etc/wireguard
    networks:
      private_network:
        ipv4_address: 10.2.0.12
    ports:
      - "51820:51820/udp"
      - "8082:51821/tcp"
    dns:
      - 10.2.0.11  # Points to pihole
      - 10.2.0.10  # Points to unbound
    environment:
      WG_PORT: 51820
      WG_PERSISTENT_KEEPALIVE: 25
      WG_DEFAULT_ADDRESS: 10.64.0.x
      WG_DEFAULT_DNS: 10.2.0.11
    env_file:
      - ./wg-easy.env
    deploy:
      resources:
        limits:
          memory: 150M
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    depends_on: [unbound]

