version: "3"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  unbound:
    image: klutchell/unbound:latest
    container_name: unbound
    hostname: unbound
    networks:
      private_network:
        ipv4_address: 10.2.0.10
    deploy:
      resources:
        limits:
          memory: 200M
    restart: on-failure:5

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    volumes:
      - /srv/homelab/wirehole/pihole/etc-pihole:/etc/pihole
      - /srv/homelab/wirehole/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      private_network:
        ipv4_address: 10.2.0.11
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
#      - 67:67/udp # Only required if you are using Pi-hole as your DHCP server.
#    cap_add:
#      - NET_ADMIN # Only required if you are using Pi-hole as your DHCP server.
    dns:
      - 127.0.0.1
      - 10.2.0.10  # Points to unbound
    environment:
      TZ: America/New_York
      WEBPASSWORD: yourpassword  # ⚠️ Set a password for pihole here.
      ServerIP: 10.2.0.100  # Internal IP of pihole
      DNS1: 10.2.0.10  # Unbound IP
      DNS2: 10.2.0.10  # If we don't specify two, it will auto pick google.
    deploy:
      resources:
        limits:
          memory: 300M
    restart: on-failure:5
    depends_on: [unbound]

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    hostname: wg-easy
    volumes: /srv/homelab/wirehole/wg-easy:/etc/wireguard \
    networks:
      private_network:
        ipv4_address: 10.2.0.12
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    dns:
      - 10.2.0.11  # Points to pihole
      - 10.2.0.10  # Points to unbound
    environment:
      WG_HOST: vpn.yoururl.com  # ⚠️ Change this to your host's public address or url.
      PASSWORD: yourpassword  # ⚠️ Set a password for wg-easy here.
      WG_PORT: 51820
      WG_PERSISTENT_KEEPALIVE: 25
      WG_DEFAULT_ADDRESS: 10.64.0.x
      WG_DEFAULT_DNS: 10.2.0.11
    deploy:
      resources:
        limits:
          memory: 200M
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: on-failure:5
    depends_on: [unbound, pihole]

