networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.40.0.0/24

services:
  unbound:
    image: klutchell/unbound:main
    container_name: unbound
    hostname: unbound
    networks:
      private_network:
        ipv4_address: 10.40.0.2
    deploy:
      resources:
        limits:
          memory: 100M
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    volumes:
      - /srv/wirehole/pihole/etc-pihole:/etc/pihole
      - /srv/wirehole/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      private_network:
        ipv4_address: 10.40.0.3
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80/tcp"
#      - 67:67/udp # Only required if you are using Pi-hole as your DHCP server.
#    cap_add:
#      - NET_ADMIN # Only required if you are using Pi-hole as your DHCP server.
    dns:
      - 10.40.0.1  # Points to unbound
    environment:
      ServerIP: 10.40.0.3  # Internal IP of pihole
      DNS1: 10.40.0.2  # Unbound IP
      DNS2: 10.40.0.2  # If we don't specify two, it will auto pick google.
    env_file:
      - ./pihole.env
    deploy:
      resources:
        limits:
          memory: 250M
    restart: unless-stopped

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    hostname: wg-easy
    volumes:
      - /srv/wirehole/wg-easy:/etc/wireguard
    networks:
      private_network:
        ipv4_address: 10.40.0.4
    ports:
      - "443:443/udp"
      - "8082:51821/tcp"
    dns:
      - 10.40.0.3  # Points to pihole
      - 10.40.0.2  # Points to unbound
    environment:
      WG_PORT: 443
      WG_PERSISTENT_KEEPALIVE: 25
      WG_DEFAULT_ADDRESS: 10.41.0.x
      WG_DEFAULT_DNS: 10.40.0.3
    env_file:
      - ./wg-easy.env
    deploy:
      resources:
        limits:
          memory: 100M
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped