---
version: "2.1"

services:
  questionable.zip:
    image: lscr.io/linuxserver/swag
    container_name: questionable.zip
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL=questionable.zip
      - SUBDOMAINS=www
      - VALIDATION=http
      - CERTPROVIDER= zerossl
      - EMAIL=jward92@gmail.com
    volumes:
      - /srv/questionable.zip:/config
    ports:
      - 443:443
      - 80:80
    restart: on-failure:5
