version: '3'

services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL=questionable.zip
      - VALIDATION=http
      - SUBDOMAINS=www
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./config:/config
    deploy:
      resources:
        limits:
          memory: 200M
    restart: unless-stopped
