services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    network_mode: host
    user: "1000:1000"
    cap_drop:
      - all
    read_only: true
    security_opt:
      - no-new-privileges:true
    env_file:
      - ./cloudflare-ddns.env
    deploy:
      resources:
        limits:
          memory: 50M
    restart: unless-stopped