title: Homepage

background:
  image: /images/background.png
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100

  cardBlur: sm # sm, "", md, etc... see https://tailwindcss.com/docs/backdrop-blur

  theme: dark # or light

  color: slate

  layout:
    Media:
      style: row
      columns: 3